from django.contrib import admin
from .models import *

admin.site.register(News)
admin.site.register(Question)
admin.site.register(Answer)
admin.site.register(Vacancy)
admin.site.register(Review)
admin.site.register(PromoCode)
admin.site.register(Company)
admin.site.register(CompanyStory)
admin.site.register(Bonus)
admin.site.register(Order)
admin.site.register(Hall)
admin.site.register(Employee)
admin.site.register(Exhibit)
admin.site.register(EmployeePosition)
admin.site.register(Exhibitions)
admin.site.register(Art_form)
admin.site.register(CustomUser)
admin.site.register(Client)
